# Generated by Django 2.1.7 on 2019-07-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sex', models.IntegerField(choices=[(1, 'samiec'), (2, 'samica')])),
                ('age', models.IntegerField(default=1)),
                ('picture', models.ImageField(default=None, upload_to='documents/')),
                ('location', models.CharField(max_length=64)),
                ('accepts_cats', models.BooleanField(default=True)),
                ('house_without_animals', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='adopcje.Category')),
            ],
        ),
    ]
