# Generated by Django 3.0.1 on 2020-01-07 14:53

import adopcje.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sex', models.IntegerField(choices=[(1, 'pies'), (2, 'suczka')], default=1)),
                ('age', models.IntegerField(default=0, validators=[adopcje.models.validate_age])),
                ('weight', models.IntegerField(default=0, validators=[adopcje.models.validate_weight])),
                ('region', models.IntegerField(choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')], default=1)),
                ('town', models.CharField(max_length=64)),
                ('accepts_cats', models.IntegerField(choices=[(1, 'tak'), (2, 'do sprawdzenia'), (3, 'eksterminator kotów ;-)')], default=1)),
                ('house_with_male_dog', models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1)),
                ('house_with_female_dog', models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1)),
                ('adoption_abroad', models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1)),
                ('description', models.TextField()),
                ('categories', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'mikropsy'), (2, 'wielkopsy'), (3, 'przegubowce'), (4, 'czarnulki'), (5, 'białaski'), (6, 'rudzielce'), (7, 'buraski'), (8, 'łaciate krówki'), (9, 'włochacze'), (10, 'młodzież'), (11, 'starszaki')], max_length=23, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('contact_data', models.CharField(max_length=64)),
                ('accepted', models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('profile', models.BooleanField(default=False)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcje.Dog')),
            ],
        ),
    ]
