# Generated by Django 2.1.7 on 2019-07-14 18:16

import adopcje.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imię', models.CharField(max_length=64)),
                ('płeć', models.IntegerField(choices=[(1, 'pies'), (2, 'suczka')])),
                ('wiek', models.IntegerField(default=0, validators=[adopcje.models.validate_age])),
                ('waga', models.IntegerField(default=0, validators=[adopcje.models.validate_weight])),
                ('zdjęcie', models.ImageField(default=None, upload_to='documents/')),
                ('województwo', models.IntegerField(choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')])),
                ('miejscowość', models.CharField(max_length=64)),
                ('akceptuje_koty', models.IntegerField(choices=[(1, 'tak'), (2, 'nie'), (3, 'do sprawdzenia')])),
                ('dom_z_psem', models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1)),
                ('dom_z_suką', models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1)),
                ('możliwy_transport', models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1)),
                ('adopcja_za_granicę', models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1)),
                ('opis', models.TextField()),
                ('dodany', models.DateTimeField(auto_now_add=True)),
                ('kategorie', models.ManyToManyField(to='adopcje.Category')),
            ],
        ),
    ]
