# Generated by Django 3.0.1 on 2020-01-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='adoption_abroad',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'nie'), (3, ' ')], default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='house_with_female_dog',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'nie'), (3, ' ')], default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='house_with_male_dog',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'nie'), (3, ' ')], default=0),
        ),
    ]
