# Generated by Django 2.1.7 on 2019-07-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='adopcja_za_granicę',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=64),
        ),
        migrations.AlterField(
            model_name='dog',
            name='akceptuje_koty',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie'), ('do sprawdzenia', 'do sprawdzenia')], max_length=64),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dom_z_psem',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=64),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dom_z_suką',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=64),
        ),
        migrations.AlterField(
            model_name='dog',
            name='możliwy_transport',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=64),
        ),
        migrations.AlterField(
            model_name='dog',
            name='płeć',
            field=models.IntegerField(choices=[('pies', 'pies'), ('suczka', 'suczka')]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='województwo',
            field=models.CharField(choices=[('dolnośląskie', 'dolnośląskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('łódzkie', 'łódzkie'), ('małopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('śląskie', 'śląskie'), ('świętokrzyskie', 'świętokrzyskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=64),
        ),
    ]
