# Generated by Django 2.1.7 on 2019-07-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='accepts_cats',
            new_name='akceptuje_koty',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='house_without_animals',
            new_name='dom_bez_innych_zwierząt',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='location',
            new_name='imię',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='categories',
            new_name='kategorie',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='name',
            new_name='miejscowość',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='transport',
            new_name='możliwy_transport',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='sex',
            new_name='płeć',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='age',
            new_name='waga',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='picture',
            new_name='zdjęcie',
        ),
        migrations.AddField(
            model_name='dog',
            name='wiek',
            field=models.IntegerField(default=1),
        ),
    ]
