# Generated by Django 3.0.1 on 2020-01-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0002_auto_20200108_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='accepts_cats',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'do sprawdzenia'), (3, 'oj, gonie kotecka!')], default=1),
        ),
    ]
