# Generated by Django 2.1.7 on 2019-07-14 13:02

import adopcje.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0002_auto_20190714_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='dom_bez_innych_zwierząt',
            new_name='adopcja_za_granicę',
        ),
        migrations.AddField(
            model_name='dog',
            name='dom_bez_psów',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='dom_bez_suczek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='województwo',
            field=models.IntegerField(choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dog',
            name='akceptuje_koty',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'nie'), (3, 'do sprawdzenia')]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='wiek',
            field=models.IntegerField(default=0, validators=[adopcje.models.validate_age]),
        ),
    ]
