# Generated by Django 2.1.7 on 2019-07-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0002_auto_20190716_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='adopcja_za_granicę',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='akceptuje_koty',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'nie'), (3, 'do sprawdzenia')], default=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dom_z_psem',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dom_z_suką',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='możliwy_transport',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'nie')], default=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='płeć',
            field=models.IntegerField(choices=[(1, 'pies'), (2, 'suczka')]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='województwo',
            field=models.IntegerField(choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')], default=1),
        ),
    ]
