# Generated by Django 2.1.7 on 2019-07-14 13:06

import adopcje.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0003_auto_20190714_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='waga',
            field=models.IntegerField(default=0, validators=[adopcje.models.validate_weight]),
        ),
    ]
