# Generated by Django 2.1.7 on 2019-07-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0003_auto_20190716_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nazwa',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='akceptuje_koty',
            new_name='accepts_cats',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='adopcja_za_granicę',
            new_name='adoption_abroad',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='wiek',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='kategorie',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='dodany',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='dom_z_psem',
            new_name='house_with_female_dog',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='dom_z_suką',
            new_name='house_with_male_dog',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='imię',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='zdjęcie',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='województwo',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='płeć',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='miejscowość',
            new_name='town',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='możliwy_transport',
            new_name='transport',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='waga',
            new_name='weight',
        ),
    ]
