# Generated by Django 2.1.7 on 2019-07-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0004_auto_20190716_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='categories',
        ),
        migrations.AddField(
            model_name='dog',
            name='categories',
            field=models.IntegerField(choices=[(1, 'wielkopsy'), (2, 'maluchy'), (3, 'czarnulki'), (4, 'białaski'), (5, 'rudzielce'), (6, 'łaciate krówki'), (7, 'kłapouszki')], default=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
