# Generated by Django 2.1.7 on 2019-07-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0005_auto_20190716_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'wielkopsy'), (2, 'maluchy'), (3, 'czarnulki'), (4, 'białaski'), (5, 'rudzielce'), (6, 'łaciate krówki'), (7, 'kłapouszki')])),
            ],
        ),
        migrations.CreateModel(
            name='DogCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcje.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='dog',
            name='categories',
        ),
        migrations.AddField(
            model_name='dogcategories',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcje.Dog'),
        ),
        migrations.AddField(
            model_name='dog',
            name='categories',
            field=models.ManyToManyField(through='adopcje.DogCategories', to='adopcje.Category'),
        ),
    ]
