# Generated by Django 2.1.7 on 2019-07-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0013_message_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcategories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcje.Category'),
        ),
        migrations.AlterField(
            model_name='dogcategories',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcje.Dog'),
        ),
    ]
