# Generated by Django 2.1.7 on 2019-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0015_auto_20190722_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_5',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_6',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
