# Generated by Django 2.1.7 on 2019-07-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0016_auto_20190722_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture_1',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
