# Generated by Django 2.1.7 on 2019-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0017_auto_20190722_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture_1',
            field=models.ImageField(default=0, upload_to='documents/'),
        ),
    ]
