# Generated by Django 2.2.3 on 2019-07-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0020_adoptionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='contact_data',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
