# Generated by Django 2.2.3 on 2019-07-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0022_auto_20190722_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture_4',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
    ]
