# Generated by Django 2.2.3 on 2019-07-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0023_auto_20190722_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture_2',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_3',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_5',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_6',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
    ]
