# Generated by Django 2.2.3 on 2019-07-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0025_auto_20190722_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_5',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
