# Generated by Django 2.2.3 on 2019-07-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0026_auto_20190722_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_10',
            new_name='beh_problems',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_11',
            new_name='children',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_1',
            new_name='dog_owner',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_7',
            new_name='dogs_place',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_15',
            new_name='e_mail',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_2',
            new_name='family_agress',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_6',
            new_name='fence',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_5',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_14',
            new_name='house_owner',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_4',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_12',
            new_name='pets_owned',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_16',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_3',
            new_name='place_type',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_13',
            new_name='prev_dog',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_8',
            new_name='time_alone',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='field_9',
            new_name='walks',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='town',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='dog',
            name='accepts_cats',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'nie'), (3, 'eksterminator kotów')], default=1),
        ),
    ]
