# Generated by Django 2.2.3 on 2019-07-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0027_auto_20190723_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='location',
            new_name='town',
        ),
    ]
