# Generated by Django 2.2.3 on 2019-07-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0028_auto_20190723_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionform',
            old_name='family_agress',
            new_name='family_agree',
        ),
        migrations.AlterField(
            model_name='dog',
            name='accepts_cats',
            field=models.IntegerField(choices=[(1, 'tak'), (2, 'do sprawdzenia'), (3, 'eksterminator kotów')], default=1),
        ),
    ]
