# Generated by Django 2.2.3 on 2019-07-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0031_dog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='picture_7',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='dog',
            name='picture_8',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
