# Generated by Django 2.2.3 on 2019-07-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0032_auto_20190724_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='e_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
