# Generated by Django 2.2.3 on 2019-07-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0033_auto_20190725_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionform',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adopcje.Dog'),
        ),
        migrations.AlterField(
            model_name='dogcategories',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adopcje.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogcategories',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adopcje.Dog'),
            preserve_default=False,
        ),
    ]
