# Generated by Django 2.2.3 on 2019-07-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0035_auto_20190725_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_5',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_6',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_7',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture_8',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
