# Generated by Django 2.2.3 on 2019-07-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0036_auto_20190725_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionform',
            name='phone',
        ),
    ]
