# Generated by Django 2.2.3 on 2019-07-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0037_remove_adoptionform_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionform',
            name='phone',
            field=models.CharField(default=111, max_length=32),
            preserve_default=False,
        ),
    ]
