# Generated by Django 2.2.4 on 2019-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0038_adoptionform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionform',
            name='fence',
            field=models.IntegerField(blank=True, choices=[(1, 'tak'), (2, 'nie')], default=1, null=True),
        ),
    ]
