# Generated by Django 2.2.4 on 2019-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0039_auto_20190818_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionform',
            name='fence',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
