# Generated by Django 2.2.4 on 2019-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0040_auto_20190818_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.IntegerField(choices=[(1, 'pies'), (2, 'suczka')], default=1),
        ),
    ]
