# Generated by Django 2.2.4 on 2019-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0043_auto_20190824_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='profile',
            field=models.BooleanField(default=False),
        ),
    ]
