# Generated by Django 2.2.4 on 2019-09-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0044_picture_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionform',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
