# Generated by Django 2.2.6 on 2019-10-19 11:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0045_auto_20190907_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogcategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dogcategories',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='categories',
        ),
        migrations.AddField(
            model_name='dog',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'mikropsy'), (2, 'wielkopsy'), (3, 'przegubowce'), (4, 'czarnulki'), (5, 'białaski'), (6, 'rudzielce'), (7, 'buraski'), (8, 'łaciate krówki'), (9, 'włochacze'), (10, 'młodzież'), (11, 'starszaki')], default=1, max_length=23),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DogCategories',
        ),
    ]
