# Generated by Django 2.2.6 on 2019-10-20 09:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0046_auto_20191019_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'mikropsy'), (2, 'wielkopsy'), (3, 'przegubowce'), (4, 'czarnulki'), (5, 'białaski'), (6, 'rudzielce'), (7, 'buraski'), (8, 'łaciate krówki'), (9, 'włochacze'), (10, 'młodzież'), (11, 'starszaki')], max_length=23, null=True),
        ),
    ]
