# Generated by Django 2.2.6 on 2019-12-03 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0047_auto_20191020_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionform',
            name='date_sent',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
