# Generated by Django 2.2.6 on 2019-12-04 17:36

import adopcje.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcje', '0048_adoptionform_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionform',
            name='expiry_date',
            field=models.DateField(default=adopcje.models.get_expiry),
        ),
        migrations.AddField(
            model_name='message',
            name='expiry_date',
            field=models.DateField(default=adopcje.models.get_expiry),
        ),
        migrations.AlterField(
            model_name='adoptionform',
            name='date_sent',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
